
-- Script START
IF NOT EXISTS (SELECT * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'Events' AND TABLE_SCHEMA = 'dbo')
BEGIN
	CREATE TABLE [dbo].[Events](
	[Id] UNIQUEIDENTIFIER default NEWID(),
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](250) NOT NULL,
	[Location] [varchar](250) NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[MaxAttendance] [int]  NOT NULL
		CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
	)	ON [PRIMARY]

END
-- Script END